import '../styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/components/header';
import HeaderMobile from '@/components/header-mobile';
import MarginWidthWrapper from '@/components/margin-width-wrapper';
import PageWrapper from '@/components/page-wrapper';
import SideNav from '@/components/side-nav';
import { Providers } from './provider';



const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Side Nav w/ Sub Menu',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <body className={`bg-white ${inter.className}`}> */}
      <body className={`bg-white dark:bg-gray-900 text-gray-950 ${inter.className}`}>
        <Providers>
        <div className="flex">
          {/* <div className="flex-1">
          <SideNav />
          </div> */}
          {/* <main className="flex-2">
            <MarginWidthWrapper>
                 <Header />
              <HeaderMobile />
               {children}
            </MarginWidthWrapper>
          </main> */}
     {/* <div className="flex-3">
          <SideNav />
          </div> */}
            <div className="flex-none w-15%">
               <SideNav />
      </div>
      <div className="flex-auto w-60%">
        <main className="flex-2">
            <MarginWidthWrapper>
                 <Header />
              <HeaderMobile />
               {children}
            </MarginWidthWrapper>
          </main>
      </div>
      <div className="flex-auto w-15%">
               <SideNav />
      </div>
        </div>
        </Providers>
      </body>
    </html>
  );
}
